name: CI/CD for the application
on: [push]
jobs:
  Hello-World-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event trigger : ${{ github.event_name }}"
      - run: echo "OS : ${{ runner.os }}"
      - run: echo "Branch : ${{ github.ref }} @ ${{ github.repository }}"

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: List up the files
        run: |
          ls ${{ github.workspace }}
